config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "pages#home"

  get "/dashboard/:school_id",to: "schools#dashboard", as: :dashboard
  
  get "/management", to: "pages#management", as: :teachers_mgmt
  get "/management/:school_id", to: "schools#management", as: :school_mgmt

  post "/teachers/:school_id/update_roaster", to: "teachers#update_roaster", as: :update_roaster
  get "/teachers/:school_id/export_roaster", to: "teachers#export_roaster", as: :export_roaster, defaults: { format: :csv }
  
  resources :schools, only: [:show]

  get "/teachers/:school_id/new", to: "teachers#new", as: :new_teacher

  resources :teachers, only: [:create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bootcamps_week.rb
class BootcampsWeek < ApplicationRecord
  has_many :teachers_availabilities, dependent: :destroy
end

app/models/school.rb
class School < ApplicationRecord
  has_many :user_schools, dependent: :destroy
  has_many :users, through: :user_schools
  has_many :teachers, dependent: :destroy
  has_many :teachers_roasters, dependent: :destroy
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  require "csv"

  belongs_to :school

  validates :github_nickname, presence: true 

  def self.import(file, school_id)
    Teacher.destroy_all
    
    CSV.foreach(file.path, headers: true) do |row|
      Teacher.create(github_nickname: row[0], school_id: school_id)
    end
  end

  def self.to_a
    Teacher.all.map do |teacher|
      teacher.github_nickname
    end
  end
end

app/models/teachers_availability.rb
class TeachersAvailability < ApplicationRecord
  # belongs_to :teachers_roaster, foreign_key: 'teacher_id', primary_key: 'teacher_id', optional: true, dependent: :destroy
  belongs_to :teachers_roaster
  belongs_to :bootcamps_week
end

app/models/teachers_roaster.rb
class TeachersRoaster < ApplicationRecord
  has_many :teachers_availabilities, dependent: :destroy
  belongs_to :school

  def to_a
    attributes.map do |k,v|
      v.class == String ? v.gsub(/\s+/, ' ') : v
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, 
          # :registerable,
          :recoverable, :rememberable, :validatable

  has_many :user_schools, dependent: :destroy
  has_many :schools, through: :user_schools
end

app/models/user_school.rb
class UserSchool < ApplicationRecord
  belongs_to :user
  belongs_to :school
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # include Pundit::Authorization

  # Pundit: allow-list approach
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @schools = current_user.schools if user_signed_in?
  end

  def management
    @schools = current_user.schools
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:dashboard, :management, :update_teachers_experience]

  def dashboard
    @teachers_availabilities = LwApi::FetchTeachersAvailabilities.call(school: @school).teachers_availabilities
    @last_update = TeachersAvailability.maximum(:updated_at)
  end

  def management
    @teachers = Teacher.where(school: @school).order(:github_nickname)
  end

  private
  
  def set_school
    @school = School.find(params[:school_id])
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  require "rest-client"
  require "json"
  require 'csv'
  
  before_action :set_teacher, only: [:edit, :update, :destroy]
  before_action :set_school, only: [:new, :update_roaster, :export_roaster]
  
  COURSE_SLUGS = ["web", "data"]

  def new
    @teacher = Teacher.new
  end

  def edit
  end

  def update
    if @teacher.update(teacher_params)
      redirect_to teachers_mgmt_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create
    @school = School.find(params.dig(:teacher, :school_id))

    if params[:teacher][:file].present?
      Teacher.import(params[:teacher][:file], @school.id)
      LwApi::FetchTeachersIds.call(params: params)
      LwApi::FetchTeachersExperience.call
      redirect_to dashboard_path(@school)
    elsif params[:teacher][:github_nickname].present?
      if Teacher.find_by(teacher_params)
        flash[:notice] = "Teacher already in database"
        redirect_to new_teacher_path(@school)
      else
        Teacher.create(teacher_params) 
        LwApi::FetchTeachersIds.call(params: params)
        LwApi::FetchTeachersExperience.call(school: @school)
        redirect_to dashboard_path(@school)
      end
    end
  end

  def destroy
    @teacher.destroy
    redirect_to school_mgmt_path(@teacher.school), status: :see_other
  end

  def update_roaster
    LwApi::FetchTeachersExperience.call(school: @school)

    redirect_to dashboard_path(@school)
  end

  def export_roaster
    @teachers_availabilities = LwApi::FetchTeachersAvailabilities.call(school: @school).teachers_availabilities

    roaster_csv = CSV.generate do |csv|
      csv.to_io.write("\xEF\xBB\xBF")
      csv << @teachers_availabilities.first.attributes.keys
      @teachers_availabilities.each do |teacher_availability|
        csv << teacher_availability.attributes.values_at(*@teachers_availabilities.first.attributes.keys)
      end
    end

    respond_to do |format|
      format.html
      format.csv do
        send_data roaster_csv,
                  filename: "teachers_roaster_#{@school.city}_#{Date.today}.csv", 
                  type: 'text/csv',
                  disposition: 'attachment'
      end
    end
  end

  private 

  def teacher_params
    params.require(:teacher).permit(:github_nickname, :school_id)
  end

  def set_teacher
    @teacher = Teacher.find(params[:id]) 
  end

  def set_school
    @school = School.find(params[:school_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LwLisbonTeachersRoaster</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="banner py-5">
  <h1 class="text-center fw-bold">Le Wagon Lisbon</h1>
  <h4 class="text-center">Teachers Roaster</h4>
  <% if user_signed_in? %>
    <div class="text-center mt-4">
      <%= link_to export_roaster_path(format: :csv), class: "btn btn-export" do %>
        Export Roaster <i class="fas fa-cloud-download-alt"></i>
      <% end %>
    </div>
  <% end %>
</div>

<% if user_signed_in? %>  
  <div class="text-center bg-white p-3">
    <% if @last_update %>
      <p class="mt-3"><strong>Last update:</strong> <%= (Date.today - @last_update.to_date).to_i %> day<%= "s" if (Date.today - @last_update.to_date).to_i != 1 %> ago (<%= @last_update.strftime("%d of %b %Y, at %H:%M") %>)</p>
    <% end %>

    <%= form_with url: update_roaster_path, method: :post do |f| %>
      <%= button_tag class: "btn btn-update" do %>
        <span class="show-when-enabled">Update Roaster</span>
        <span class="show-when-disabled"><i class='fa fa-spinner fa-spin'></i> Updating</span>
      <% end %>
    <% end %>
  </div>
  
  <div class="py-4 bg-white">
    <table class="table table-hover custom-table">
      <tr>
        <th class="first-table-th custom-th">Course</th>
        <th class="custom-th">Week</th>
        <th class="custom-th">Lecture</th>
        <th class="custom-th">Teacher Id</th>
        <th class="custom-th">Teacher</th>
        <th class="custom-th">Github Nickname</th>
        <th class="custom-th">Days as LT</th>
        <th class="custom-th">Days as LTA</th>
        <th class="custom-th">Days as TA</th>
        <th class="custom-th">Location</th>
        <th class="last-table-th custom-th">Kitt Profile</th>
      </tr>
      <tbody>
        <% @teachers_availabilities.each do |availability| %>
          <tr class="position-relative">
            <td><%= availability.course_slug %></td>
            <td><%= availability.week %></td>
            <td><%= availability.lecture_day_slug %></td>
            <td><%= availability.teacher_id %></td>
            <td><%= availability.first_name %> <%= availability.last_name %></td>
            <td><%= availability.github_nickname %></td>
            <td style="<%= "color: rgba(0,0,0,0.1)" if availability.lecturer_work_day_count == 0 %>"><%= availability.lecturer_work_day_count %></td>
            <td style="<%= "color: rgba(0,0,0,0.1)" if availability.lead_ta_work_day_count == 0 %>"><%= availability.lead_ta_work_day_count %></td>
            <td style="<%= "color: rgba(0,0,0,0.1)" if availability.ta_work_day_count == 0 %>"><%= availability.ta_work_day_count %></td>
            <td><%= availability.country_of_residence %> - <%= availability.city_of_residence %></td>
            <td><%= link_to availability.teacher_profile_url, availability.teacher_profile_url, style: "color: black", target: "a_blank" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="sign-up-container mt-5">
    <h2 class="text-center">Log in</h2>

    <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name), data: { turbo: :false }) do |f| %>
      <div class="form-inputs">
        <%= f.input :email,
                    required: false,
                    autofocus: true,
                    input_html: { autocomplete: "email" } %>
        <%= f.input :password,
                    required: false,
                    input_html: { autocomplete: "current-password" } %>
        <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
      </div>

      <div class="form-actions text-center">
        <%= f.button :submit, "Log in", class: "btn btn-dark" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/pages/home.html.erb
<div class="banner py-5">
  <h1 class="text-center fw-bold">Le Wagon</h1>
  <h4 class="text-center">Teachers Roasters</h4>
</div>
  
<% if user_signed_in? %> 
  <div class="schools-grid mt-4">
    <% @schools.each do |school| %>
      <div class="school-card text-center">
        <%= link_to school.city, dashboard_path(school), class: "btn" %>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="sign-up-container mt-5">
    <h2 class="text-center">Log in</h2>

    <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name), data: { turbo: :false }) do |f| %>
      <div class="form-inputs">
        <%= f.input :email,
                    required: false,
                    autofocus: true,
                    input_html: { autocomplete: "email" } %>
        <%= f.input :password,
                    required: false,
                    input_html: { autocomplete: "current-password" } %>
        <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
      </div>

      <div class="form-actions text-center">
        <%= f.button :submit, "Log in", class: "btn btn-dark" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/pages/management.html.erb
<div class="banner py-5">
  <h1 class="text-center"><strong>Le Wagon</strong></h1>
  <h4 class="text-center">My Campus</h4>
</div>

<div class="mt-4" style="width: 250px;margin: 0 auto;">
  <% @schools.each do |school| %>
    <div class="school-card text-center">
      <%= link_to  school_mgmt_path(school), class: "btn" do %>
        <i class="fa-solid fa-gear"></i> <%= school.city %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/schools/dashboard.html.erb
<div class="banner py-5">
  <h1 class="text-center fw-bold">Le Wagon <span style="color: #E60E05; font-weight: bold;"><%= @school.city.capitalize %></span></h1>
  <h4 class="text-center">Teachers Roaster</h4>
  <% if user_signed_in? %>
    <div class="text-center mt-4">
      <%= link_to export_roaster_path(format: :csv), class: "btn btn-export" do %>
        Export Roaster <i class="fas fa-cloud-download-alt"></i>
      <% end %>
    </div>
  <% end %>
</div>

<% if user_signed_in? %>  
  <div class="text-center bg-white p-3">
    <% if @last_update %>
      <p class="mt-3"><strong>Last update:</strong> <%= (Date.today - @last_update.to_date).to_i %> day<%= "s" if (Date.today - @last_update.to_date).to_i != 1 %> ago (<%= @last_update.strftime("%d of %b %Y, at %H:%M") %>)</p>
    <% end %>

    <%= form_with url: update_roaster_path(@school, format: "csv"), method: :post do |f| %>
      <%= button_tag class: "btn btn-update" do %>
        <span class="show-when-enabled">Update Roaster</span>
        <span class="show-when-disabled"><i class='fa fa-spinner fa-spin'></i> Updating</span>
      <% end %>
    <% end %>
  </div>
  
  <div class="py-4 bg-white">
    <table class="table table-hover custom-table">
      <tr>
        <th class="first-table-th custom-th">Course</th>
        <th class="custom-th">Topic</th>
        <th class="custom-th">Week</th>
        <th class="custom-th">Lecture</th>
        <th class="custom-th">Teacher Id</th>
        <th class="custom-th">Teacher</th>
        <th class="custom-th">Github Nickname</th>
        <th class="custom-th">Days as LT</th>
        <th class="custom-th">Days as LTA</th>
        <th class="custom-th">Days as TA</th>
        <th class="custom-th">Location</th>
        <th class="last-table-th custom-th">Kitt Profile</th>
      </tr>
      <tbody>
        <% @teachers_availabilities.each do |availability| %>
          <tr class="position-relative">
            <td><%= availability.course_slug %></td>
            <td><%= availability.topic %></td>
            <td><%= availability.week %></td>
            <td><%= availability.lecture_day_slug %></td>
            <td><%= availability.teacher_id %></td>
            <td><%= availability.first_name %> <%= availability.last_name %></td>
            <td><%= availability.github_nickname %></td>
            <td style="<%= "color: rgba(0,0,0,0.1)" if availability.lecturer_work_day_count == 0 %>"><%= availability.lecturer_work_day_count %></td>
            <td style="<%= "color: rgba(0,0,0,0.1)" if availability.lead_ta_work_day_count == 0 %>"><%= availability.lead_ta_work_day_count %></td>
            <td style="<%= "color: rgba(0,0,0,0.1)" if availability.ta_work_day_count == 0 %>"><%= availability.ta_work_day_count %></td>
            <td><%= availability.country_of_residence %> - <%= availability.city_of_residence %></td>
            <td><%= link_to availability.teacher_profile_url, availability.teacher_profile_url, style: "color: black", target: "a_blank" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="sign-up-container mt-5">
    <h2 class="text-center">Log in</h2>

    <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name), data: { turbo: :false }) do |f| %>
      <div class="form-inputs">
        <%= f.input :email,
                    required: false,
                    autofocus: true,
                    input_html: { autocomplete: "email" } %>
        <%= f.input :password,
                    required: false,
                    input_html: { autocomplete: "current-password" } %>
        <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
      </div>

      <div class="form-actions text-center">
        <%= f.button :submit, "Log in", class: "btn btn-dark" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/schools/management.html.erb
<div class="banner py-5">
  <h1 class="text-center"><strong>Le Wagon</strong></h1>
  <h4 class="text-center"><span style="color: #E60E05; font-weight: bold;"><%= @school.city %></span> Campus</h4>
</div>

<div class="mt-5 text-center">
  <%= link_to "Upload Teachers", new_teacher_path, class: "btn btn-update d-block mx-auto mb-3", style: "width: 200px" %>
</div>

<div class="mt-5">
  <div class="alert-teachers">
    <i class="fa-solid fa-bell position-absolute" style="color: rgb(230,14,5)"></i>
    <p class="m-0">Teacher not present in the API (no classes given ever).</p>
  </div>

  <table class="teachers-mgmt-table">
    <tr>
      <th class="only-table-th custom-th">Github Nickname</th>
    </tr>
    <% @teachers.each do |teacher| %>
      <tr class="position-relative">
        <td style=<%= TeachersRoaster.find_by(github_nickname: teacher.github_nickname) ? "" : "background:" + "rgba(230,14,5,0.1);" %>>
          <%= teacher.github_nickname %>
          <%= link_to edit_teacher_path(teacher), class: "position-absolute edit-btn" do %>
            <i class="fa-solid fa-pen-to-square"></i>
          <% end %>

          <%= link_to teacher_path(teacher), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "position-absolute delete-btn" do %>
            <i class="fa-solid fa-trash"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto align-items-center">
        <% if user_signed_in? %>
          <%# <li class="nav-item active"> %>
            <%#= link_to "+ Add teachers", "#", class: "nav-link btn btn-export" %>
          <%# </li> %>
          <li class="nav-item active <%= "fw-bold" if action_name == "home" %>">
            <%= link_to "My Teachers Roasters", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item active <%= "fw-bold" if action_name == "management" %>">
            <%= link_to "Manage Campus", teachers_mgmt_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log-out", destroy_user_session_path, class: "nav-link", data: { turbo_method: :delete } %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log-in", root_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/teachers/edit.html.erb
<div class="sign-up-container mt-5">
  <%= simple_form_for @teacher, data: { turbo: :false } do |f| %>
    <h2 class="text-center mb-3">Edit Teacher</h2>

    <div class="form-inputs">
      <%= f.input :github_nickname,
                  required: true,
                  input_html: { autocomplete: "github-nickname" } %>
    </div>

    <div class="form-actions text-center">
      <%= f.button :submit, "Save", class: "btn btn-update" %>
    </div>
  <% end %>
</div>

app/views/teachers/management.html.erb
<h1 class="mt-5 text-center"><strong>Le Wagon</strong></h1>
<h2 class="text-center">My Teachers</h2>

<div class="mt-5 text-center">
  <%= link_to "Upload Teachers", new_teacher_path, class: "btn btn-update" %>
</div>

<div class="schools-grid mt-4">
  <% @schools.each do |school| %>
    <div class="school-card text-center">
      <%= link_to school.city, dashboard_path(school), class: "btn" %>
    </div>
  <% end %>
</div>

app/views/teachers/management_old.html.erb
<h1 class="mt-5 text-center"><strong>Le Wagon</strong></h1>
<h2 class="text-center">Lisbon Teachers</h2>

<div class="mt-5 text-center">
  <%= link_to "Upload Teachers", new_teacher_path, class: "btn btn-update" %>
</div>

<div class="mt-5">
  <div class="alert-teachers">
    <i class="fa-solid fa-bell position-absolute" style="color: rgb(230,14,5)"></i>
    <p class="m-0">Teacher not present in the API (no classes given ever).</p>
  </div>

  <table class="teachers-mgmt-table">
    <tr>
      <th class="only-table-th custom-th">Github Nickname</th>
    </tr>
    <% @teachers.each do |teacher| %>
      <tr class="position-relative">
        <td style=<%= TeachersRoaster.find_by(github_nickname: teacher.github_nickname) ? "" : "background:" + "rgba(230,14,5,0.1);" %>>
          <%= teacher.github_nickname %>
          <%= link_to edit_teacher_path(teacher), class: "position-absolute edit-btn" do %>
            <i class="fa-solid fa-pen-to-square"></i>
          <% end %>

          <%= link_to teacher_path(teacher), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "position-absolute delete-btn" do %>
            <i class="fa-solid fa-trash"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/teachers/new.html.erb
<div class="banner py-5">
  <h1 class="text-center fw-bold">Le Wagon</h1>
  <h4 class="text-center"><span style="color: #E60E05; font-weight: bold;"><%= @school.city %></span> Campus</h4>
</div>

<div class="d-flex justify-content-between align-items-center mt-5">
  <div class="sign-up-container mt-5">
    <h2 class="text-center mb-3">Teacher Form</h2>

    <%= form_with url: teachers_path, model: @teacher, method: :post do |f| %>
      <div class="form-inputs">
        <%= f.label "Github Nickname", class: "form-label email optional" %>
        <%= f.hidden_field :school_id, value: @school.id %>
        <%= f.text_field :github_nickname,
                    required: true,
                    input_html: { autocomplete: "github-nickname" },
                    class: "form-control string email optional" %>
      </div>

      <div class="form-actions text-center mt-3">
        <%= button_tag class: "btn btn-update" do %>
          <span class="show-when-enabled">+ Add Teacher</span>
          <span class="show-when-disabled"><i class='fa fa-spinner fa-spin'></i> Adding Teacher & Updating Roaster</span>
        <% end %>
      </div>

    <% end %>
  </div>

  <h3 class="text-center my-4" style="color: rgb(103,11,255);"><strong>OR</strong></h3>

  <div class="sign-up-container mt-4 mb-4">
    <h2 class="text-center mb-3">Teachers CSV</h2>
    <div class="text-center">
      <p style="font-size: 14px">csv example:</p>
      <%= image_tag "csv_upload_example.png", height: "150px" %>
    </div>

    <%= form_with url: teachers_path, model: @teacher, method: :post do |f| %>
      <div class="form-actions mt-3 text-center">
        <%= f.hidden_field :school_id, value: @school.id %>
        <%= f.file_field :file, required: true, class: "form-control file required" %>
      </div>

      <div class="form-actions text-center mt-3">
        <%= button_tag class: "btn btn-export" do %>
          <span class="show-when-enabled">Upload</span>
          <span class="show-when-disabled"><i class='fa fa-spinner fa-spin'></i> Uploading & Updating Roaster</span>
        <% end %>
      </div>
    <% end %>
    <p class="mt-2 mb-0" style="font-size: 12px"><i>*This action will replace previously uploaded teachers.</i></p>
  </div>
</div>